services:
  astro-chef:
    image: "ghcr.io/moxie0420/astro-chef:latest"
    restart: always
    env_file:
      - .env.prod
    ports:
      - 80:4321
    volumes:
      - astroChef:/data
    depends_on:
      - db
    networks:
      - db

  db:
    image: "postgres:16-alpine"
    restart: always
    shm_size: 128mb
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    volumes:
      - astroChefDB:/var/lib/postgresql/data
    networks:
      - db

volumes:
  astroChef:
  astroChefDB:
    driver: local

networks:
  db:
    driver: bridge
