services:
  astro-chef:
    image: "astro-chef:latest"
    env_file:
      - .env.prod
    ports:
      - 80:4321
    volumes:
      - localData:/data
    depends_on:
      - db
    networks:
      - db

  db:
    image: "postgres:alpine"
    restart: always
    shm_size: 128mb
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    volumes:
      - astroChefDB:/var/lib/postgresql/data
    networks:
      - db

  ftp:
    image: "drakkan/sftpgo"
    restart: always
    env_file:
      - .env.prod
    ports:
      - 8080:8080
      - 2022:2022
    volumes:
      - localData:/srv/sftpgo
      - localData:/var/lib/sftpgo

volumes:
  localData:
  astroChefDB:
    driver: local

networks:
  db:
    driver: bridge
