services:
  astro-chef:
    image: "astro-chef:latest"
    env_file:
      - .env
    ports:
      - 4321:4321
    volumes:
      - astroChef:/data
    depends_on:
      - db
    networks:
      - db

  db:
    image: "postgres:alpine"
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - astroChefDB:/var/lib/postgresql/data
    networks:
      - db

volumes:
  astroChef:
    driver: local
  astroChefDB:
    driver: local

networks:
  db:
    driver: bridge
