services:
  astro-chef:
    image: "astro-chef:latest"
    ports:
      - "4321:4321"
      - "8080:8080"
    volumes:
      - ./data:/data

  postgres:
    image: "postgres:15"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
