services:
  astro-chef:
    image: "ghcr.io/moxie0420/astro-chef:latest"
    restart: always
    env_file:
      - .env
    ports:
      - 80:4321
    volumes:
      - astroChef:/data
    depends_on:
      - db

  db:
    image: "postgres:16-alpine"
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  astroChef:
  db:
