name: AstroChef

services:
  db:
    image: "postgres:16-alpine"
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:5432

  storage:
    image: "quay.io/minio/minio"
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: minio server /data --console-address ":9001"
    volumes:
      - images:/data

volumes:
  images:
