/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}",
    "./node_modules/flowbite/**/*.js",
  ],
  theme: {
    colors: {
      base: "#191724",
      surface: "#1f1d2e",
      overlay: "#26233a",
      muted: "#6e6a86",
      subtle: "#908caa",
      text: "#e0def4",
      love: "#eb6f92",
      gold: "#f6c177",
      rose: "#ebbcba",
      pine: "#31748f",
      foam: "#9ccfd8",
      iris: "#c4a7e7",
      highlightLow: "#21202e",
      highlightMed: "#403d52",
      highlightHigh: "#524f67",
    },
    extend: {
      typography: ({ theme }) => ({
        rosePine: {
          css: {
            "--tw-prose-body": theme("colors.rosePine.text"),
            "--tw-prose-headings": theme("colors.rosePine.text"),
            "--tw-prose-lead": theme("colors.rosePine.text"),
            "--tw-prose-links": theme("colors.rosePine.text"),
            "--tw-prose-bold": theme("colors.rosePine.text"),
            "--tw-prose-counters": theme("colors.rosePine.text"),
            "--tw-prose-bullets": theme("colors.rosePine.text"),
            "--tw-prose-hr": theme("colors.rosePine.text"),
            "--tw-prose-quotes": theme("colors.rosePine.text"),
            "--tw-prose-quote-borders": theme("colors.rosePine.text"),
            "--tw-prose-captions": theme("colors.rosePine.text"),
            "--tw-prose-code": theme("colors.rosePine.text"),
            "--tw-prose-pre-code": theme("colors.rosePine.text"),
            "--tw-prose-pre-bg": theme("colors.rosePine.text"),
            "--tw-prose-th-borders": theme("colors.rosePine.text"),
            "--tw-prose-td-borders": theme("colors.rosePine.text"),
            "--tw-prose-invert-body": theme("colors.rosePine.text"),
            "--tw-prose-invert-headings": theme("colors.rosePine.text"),
            "--tw-prose-invert-lead": theme("colors.rosePine.text"),
            "--tw-prose-invert-links": theme("colors.rosePine.text"),
            "--tw-prose-invert-bold": theme("colors.rosePine.text"),
            "--tw-prose-invert-counters": theme("colors.rosePine.text"),
            "--tw-prose-invert-bullets": theme("colors.rosePine.text"),
            "--tw-prose-invert-hr": theme("colors.rosePine.text"),
            "--tw-prose-invert-quotes": theme("colors.rosePine.text"),
            "--tw-prose-invert-quote-borders": theme("colors.rosePine.text"),
            "--tw-prose-invert-captions": theme("colors.rosePine.text"),
            "--tw-prose-invert-code": theme("colors.rosePine.text"),
            "--tw-prose-invert-pre-code": theme("colors.rosePine.text"),
            "--tw-prose-invert-pre-bg": theme("colors.rosePine.text"),
            "--tw-prose-invert-th-borders": theme("colors.rosePine.text"),
            "--tw-prose-invert-td-borders": theme("colors.rosePine.text"),
          },
        },
      }),
      colors: {
        rosePine: {
          base: "#191724",
          surface: "#1f1d2e",
          overlay: "#26233a",
          muted: "#6e6a86",
          subtle: "#908caa",
          text: "#e0def4",
          love: "#eb6f92",
          gold: "#f6c177",
          rose: "#ebbcba",
          pine: "#31748f",
          foam: "#9ccfd8",
          iris: "#c4a7e7",
          highlightLow: "#21202e",
          highlightMed: "#403d52",
          highlightHigh: "#524f67",
        },
        rosePineMoon: {
          base: "#232136",
          surface: "#2a273f",
          overlay: "#393552",
          muted: "#6e6a86",
          subtle: "#908caa",
          text: "#e0def4",
          love: "#eb6f92",
          gold: "#f6c177",
          rose: "#ea9a97",
          pine: "#3e8fb0",
          foam: "#9ccfd8",
          iris: "#c4a7e7",
          highlightLow: "#2a283e",
          highlightMed: "#44415a",
          highlightHigh: "#56526e",
        },
        rosePineDawn: {
          base: "#faf4ed",
          surface: "#fffaf3",
          overlay: "#f2e9e1",
          muted: "#9893a5",
          subtle: "#797593",
          text: "#575279",
          love: "#b4637a",
          gold: "#ea9d34",
          rose: "#d7827e",
          pine: "#286983",
          foam: "#56949f",
          iris: "#907aa9",
          highlightLow: "#f4ede8",
          highlightMed: "#dfdad9",
          highlightHigh: "#cecacd",
        },
        kitchen: {
          bg: "#f4f1de",
          fg: "#3d405b",
          primary: "#81b29a",
          secondary: "#e07a5f",
          accent: "#f2cc8f",
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("flowbite/plugin"),
  ],
};
