CREATE TABLE "Ingredients" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Ingredients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recipeId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"unit" varchar(255) NOT NULL,
	"whole" real NOT NULL,
	"fraction" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Recipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Recipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) DEFAULT 'No title yet' NOT NULL,
	"author" varchar(255) DEFAULT 'No author yet' NOT NULL,
	"created" timestamp DEFAULT now(),
	"edited" timestamp DEFAULT now(),
	"prepTime" varchar(255) DEFAULT '' NOT NULL,
	"cookTime" varchar(255) DEFAULT '' NOT NULL,
	"description" varchar(255) DEFAULT 'No description yet' NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"image" varchar(255) DEFAULT '/default.png' NOT NULL,
	"imageAlt" varchar(255) DEFAULT 'default image' NOT NULL,
	"liked" boolean DEFAULT false NOT NULL,
	"totalViews" integer DEFAULT 0 NOT NULL
);
