---
name: diff-lcs
version: '1.5'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 815e8f97e0be3127ccdb09c4bfe3908797f937d6
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
