name: "Build & Cache"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/flakehub-cache-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: astro-chef
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix build
      - run: nix run nixpkgs#skopeo -- login --username ${{github.actor}} --password ${{secrets.GITHUB_TOKEN}} ghcr.io
      - run: nix run nixpkgs#skopeo -- copy docker-archive:./result "docker://ghcr.io/moxie0420/astro-chef"
